In [46]:
import numpy as np

In [48]:
#DOT PRODUCT OF TWO MATRICES

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
          [0,0,0],
          [0,0,0]]

for i in range(len(X)):
   for j in range(len(X[0])):
       result[i][j] = X[i][j] * Y[i][j]

for r in result:
   print(r)

[60, 56, 3]
[24, 35, 18]
[28, 40, 81]


In [23]:
# TRANSPOSE OF A MATRIX

X1 = [[12,7],
    [4 ,5],
    [3 ,8]]


result1 = [[0,0,0],
         [0,0,0]]

for i in range(len(X1)):
  for j in range(len(X1[0])):
       result1[j][i] = X1[i][j]
      
for r in result1:
   print(r)


[12, 4, 3]
[7, 5, 8]


In [38]:
# TRACE OF A MATRIX

X2 = np.matrix('[12,7,3; 4,5,6; 7,8,9]')
tra = X2.trace()
print(tra)


[[26]]


In [36]:
# RANK OF A MATRIX

my_matrix = np.array([[1, 2, 1], [3, 4, 7], [3, 6, 3]])
print("Matrix")
for row in my_matrix:
    print(row)
    rank = np.linalg.matrix_rank(my_matrix)
print("Rank of the given Matrix is : ",rank)

Matrix
[1 2 1]
[3 4 7]
[3 6 3]
Rank of the given Matrix is :  2


In [45]:
#DETERMINANT OF A MATRIX

X3 = np.array([[4,2], [3,4]])
d = np.linalg.det(X3)

print(d)

10.000000000000002
