In [40]:
import numpy as np
A = int(input("Enter the number of rows:"))


Enter the number of rows:2


In [41]:
B = int(input("Enter the number of columns:"))

Enter the number of columns:2


In [42]:
matrix1 = []
print("Enter the values:")

Enter the values:


Enter the values:


In [44]:
for i in range(A):         
    c =[]
    for j in range(B):      
         c.append(int(input()))
    matrix1.append(c)

10
20
30
40


In [45]:
for i in range(A):
    for j in range(B):
        print(matrix1[i][j], end = " ")
    print()

10 20 
30 40 


In [46]:
A = int(input("Enter the number of rows:"))


Enter the number of rows:2


In [47]:
B = int(input("Enter the number of columns:"))

Enter the number of columns:2


In [48]:

matrix2 = []
print("Enter the values:")


Enter the values:


In [49]:
for i in range(A):         
    d =[]
    for j in range(B):      
         d.append(int(input()))
    matrix2.append(d)

50
60
70
80


In [50]:
for i in range(A):
    for j in range(B):
        print(matrix2[i][j], end = " ")
    print()

50 60 
70 80 


In [51]:
#to find the dot product of the matrixes
x=np.dot(matrix1, matrix2)  
  

In [52]:
x

array([[1900, 2200],
       [4300, 5000]])

In [53]:
#to transpose the matrix
np.transpose(matrix1)

array([[10, 30],
       [20, 40]])

In [54]:

np.transpose(matrix2)

array([[50, 70],
       [60, 80]])

In [55]:
#to trace the matrix ie; sum of the daigonals
np.trace(matrix1)


50

In [56]:
np.trace(matrix2)


130

In [58]:
#rank ie;linear independent rows or columns
np.linalg.matrix_rank(matrix1)

2

In [59]:
np.linalg.matrix_rank(matrix2)

2

In [60]:
#determinant of the mathrix
np.linalg.det(matrix1)


-200.0000000000001

In [61]:
np.linalg.det(matrix2)


-199.99999999999974