In [26]:
import numpy as np
import pandas as pd

In [31]:
a=np.arange(0,9).reshape(3,3)
print(a)
b=np.arange(1,10).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
r=np.transpose(a)
print(r)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [33]:
np.trace(a)

12

In [34]:
b=np.arange(1,10).reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
r=np.dot(a,b)
print(r)

[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]


In [39]:
a.shape

(3, 3)

In [47]:
np.linalg.det(b)

0.0

In [52]:
np.linalg.matrix_rank(a)

2