In [70]:
import numpy as np
import pandas as pd

In [89]:
rows=int(input("Give the number of rows:"))
cols=int(input("Give the number of cols:"))

Give the number of rows:3
Give the number of cols:3


In [91]:
matrix1 = [[int(input()) for c in range (cols)] for r in range(rows)]
matrix1

4
8
4
1
2
4
3
7
3


[[4, 8, 4], [1, 2, 4], [3, 7, 3]]

In [93]:
matrix2 = [[int(input()) for c in range (cols)] for r in range(rows)]
matrix2

4
3
2
1
6
4
3
2
4


[[4, 3, 2], [1, 6, 4], [3, 2, 4]]

In [94]:
from numpy.linalg.linalg import dot
print("Dot product:\n", dot(matrix1,matrix2))

Dot product:
 [[36 68 56]
 [18 23 26]
 [28 57 46]]


In [95]:
np.transpose(matrix1)


array([[4, 1, 3],
       [8, 2, 7],
       [4, 4, 3]])

In [96]:
np.trace(matrix1)

9

In [97]:
from numpy.linalg import matrix_rank
matrix_rank(matrix1)

3

In [98]:
print(np.linalg.det(matrix1))

-12.0
